version: '2'

services:
#  keycloak:
#    image: 'jboss/keycloak'
#    ports:
#      - '8080:8080'
#      - '9990:9990'
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
#  mongo:
#    image: mongo
#    ports:
#      - 27017:27017